### ISSUE TITLE
An unexpected error occured, maybe a bug.

### ISSUE THREAD

**Issue by brianNnelson** [andersevenrud/OS.js-v2#197] opened 2015-12-30 18:01 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: 
Line: 0:0
Message: Script error.
```

**Comment by andersevenrud** [comment] 2015-12-30 18:03
Thanks for reporting!

It seems that this is a problem for some users and I have yet to find out why. It still works after you close the error, right ?

Duplicate of: #185

**Closed by andersevenrud** 2015-12-30 18:03 UTC

**Comment by brianNnelson** [comment] 2015-12-30 18:13
Yes it does work after I closed the error window.

**Comment by andersevenrud** [comment] 2015-12-30 18:14
Good. Then at least nothing breaks. What browser and OS do you use ? And do you have any plugins/extensions running ? 

Trying to gather some information on this to help be debug

**Comment by brianNnelson** [comment] 2015-12-30 19:18
Win7 OS, Chrome Version 47.0.2526.106 m
