### ISSUE TITLE
An unexpected error occured, maybe a bug.

### ISSUE THREAD

**Issue by thakerhardiks** [andersevenrud/OS.js-v2#236] opened 2016-01-03 18:14 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
Error: Cannot doLaunchFile() without a mime type
    at Object.doLaunchFile [as open] (http://osjsv2.0o.no/osjs.js:1622:32)
    at http://osjsv2.0o.no/packages/default/FileManager/combined.js:266:11
    at Array.forEach (native)
    at ApplicationFileManagerWindow.checkActivation (http://osjsv2.0o.no/packages/default/FileManager/combined.js:260:19)
    at UIElement.<anonymous> (http://osjsv2.0o.no/packages/default/FileManager/combined.js:177:14)
    at HTMLElement.cbNormal (http://osjsv2.0o.no/osjs.js:1078:18)
    at UIElement.<anonymous> (http://osjsv2.0o.no/osjs.js:6821:10)
    at HTMLElement.cbNormal (http://osjsv2.0o.no/osjs.js:1078:18)
    at HTMLElement.activate (http://osjsv2.0o.no/osjs.js:5640:12)
    at HTMLElement.cbNormal (http://osjsv2.0o.no/osjs.js:1078:18)
```

**Comment by andersevenrud** [comment] 2016-01-03 18:17
What file did you try to open ?

**Comment by andersevenrud** [comment] 2016-01-04 17:17
These turns out to be broken/corrupted files and not a bug :)

Duplicate of: #239

**Closed by andersevenrud** 2016-01-04 17:17 UTC
Labels: duplicate
