### ISSUE TITLE
Double click js file on file explorer cause this 'JavaScript error report'

### ISSUE THREAD

**Issue by jimmyliao** [andersevenrud/OS.js-v2#215] opened 2015-12-31 17:07 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
ApplicationFileManagerWindow.prototype.changePath/<.done@http://159.122.251.31:8000/packages/default/FileManager/combined.js:399:11
@http://159.122.251.31:8000/osjs.js:7042:13
readdir/<@http://159.122.251.31:8000/osjs.js:6896:7
scandir/<@http://159.122.251.31:8000/osjs.js:6853:7
OSjs.VFS.scandir/<@http://159.122.251.31:8000/osjs.js:9286:7
_NullModule.scandir/<@http://159.122.251.31:8000/osjs.js:9745:7
internalCall/<@http://159.122.251.31:8000/osjs.js:9023:9
doAPICall/<@http://159.122.251.31:8000/osjs.js:1614:9
_Handler.prototype.callAPI/data.onsuccess@http://159.122.251.31:8000/osjs.js:8712:9
onReadyStateChange@http://159.122.251.31:8000/osjs.js:1140:11

```

**Comment by andersevenrud** [comment] 2015-12-31 17:09
Thanks for reporting! :)

This is a duplicate of  #203 and will be looked into ASAP

**Closed by andersevenrud** 2015-12-31 17:09 UTC
Labels: duplicate
