### ISSUE TITLE
123

### ISSUE THREAD

**Issue by kewlgreen** [andersevenrud/OS.js-v2#260] opened 2016-01-14 00:03 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationGmailWindow.updateStatusBar (http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:1681:33)
    at Object.self.mailer.getMessages.onMessageQueue (http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:2348:17)
    at _next (http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:889:14)
    at http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:909:11
    at finished (http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:1058:10)
    at http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:1080:13
    at IDBRequest.request.onsuccess (http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:135:7)
```

**Comment by andersevenrud** [comment] 2016-01-14 07:45
Duplicate of #216

**Closed by andersevenrud** 2016-01-14 07:45 UTC
