### ISSUE TITLE
Some features OS.jsv2 need :)

### ISSUE THREAD

**Issue by khoaakt** [andersevenrud/OS.js-v2#100] opened 2015-04-27 12:42 UTC
**This issue has been moved to #49**

- [ ] MusicPlayer: Volume adjustment
- [ ] FileManager: Back/Forward navigation etc.
- [ ] Spreadsheet Application
- [ ] Presentation Application
- [ ] Move Appstore from settings to dedicated App
- [ ] Widgets and/or a Dockbar
- [ ] "New File" in context menus for FileView(s)
- [ ] Cut/Copy/Paste files (is actually in development)
- [ ] Application filtering/searching in "Touch Menu"
- [ ] Web-installer (basically a index.php file that sets up OS.js for you) - With update OS function
- [ ] Being able to select multiple entries in a View

Original Message:

> I have a collection of features that OS.jsv2 need to add :p 
> In media player: need a volume bar, a repeat button,... and a picture of song :)
> In file manager: add back, forward button
> In setting: remove app store and put it in an app
> In environment(desktop): add view type, sort by, new context menu,... and COPY, PASTE, CUT :lol 
> In Office app: add presentation app, spreadsheet too
> In Mulitimedia: add a video viewer app
> In OS: add login, register function
> In installer: can install in web, don't just support in VM
> That's what I want OS.jsv2 to have ;). You can look at some eyeOS app source :P

**Comment by andersevenrud** [comment] 2015-04-27 12:59
> In media player: need a volume bar, a repeat button,... and a picture of song :)

It's techically just a music player. If I ever create a "Media Player", this will  be one of the features

> In file manager: add back, forward button

Yeah. I want this too :)

> In environment(desktop): add view type, sort by, new context menu

You're thinking about the icon view ? I really should add "new file" in context. Thanks.

> ,... and COPY, PASTE, CUT :lol 

I started implementation of this in FileManager. Will finish it some day ;)

> In Office app: add presentation app, spreadsheet too

If you know about a good presentation and/or spreadsheet library then add it there. I won't go through the hassle of making my own, hehe.

> In Mulitimedia: add a video viewer app

You can view videos with "Preview" application :)

> In OS: add login, register function

This is already provided in the source. By default it is configured to use the "demo" handler wich does not need any login.

Also, registration is a bad idea on the live demo site. I had this a year ago... but after doing some analytics it turns out >50% of the users visiting simply closed the page immediately because they had to register. It's better to get them straight into the action!

> In installer: can install in web, don't just support in VM

You don't need a VM ;)

I'll look more into a web-installer later.

**Comment by khoaakt** [comment] 2015-04-27 13:10
oh, i have a bad bug :P. The media player can't seek music when music name have Hieroglyphs.
Like this: 
![image](https://cloud.githubusercontent.com/assets/6000592/7348168/6c8a7470-ed19-11e4-9681-0faad124c0fc.png)

**Comment by andersevenrud** [comment] 2015-04-27 13:11
> oh, i have a bad bug :P. The media player can't seek music when music name have Hieroglyphs.

This is not a bug. It says "seek unavailable in format" which means **the browser** cannot do it ;)

**Comment by andersevenrud** [comment] 2015-04-27 13:11
E.g: It is a problem with the file

**Comment by khoaakt** [comment] 2015-04-27 13:13
okay, but this one: 
![image](https://cloud.githubusercontent.com/assets/6000592/7348199/b837d034-ed19-11e4-8751-a61a2dcd7f0d.png)
I rename the first file and here it is
![image](https://cloud.githubusercontent.com/assets/6000592/7348214/ccd0a192-ed19-11e4-8c74-254da6d71ae9.png)

**Comment by andersevenrud** [comment] 2015-04-27 13:29
How did you get that error ? I just visited your server (with the address you left ther) and when I double-clicked the file I got no error. Did you do something else ?

I downloaded the mp3 file to my computer just in case. It might be nice to have for testing.

**Comment by khoaakt** [comment] 2015-04-27 13:32
a ha! i missed that ^_^~. You need add dockbar, gadget feature to OS.js
Like this:
![image](https://cloud.githubusercontent.com/assets/6000592/7348501/61f3dbd4-ed1c-11e4-9531-ece7ba357799.png)

**Comment by andersevenrud** [comment] 2015-04-27 13:33
Now I see... you tried to rename or move the file ?

**Comment by andersevenrud** [comment] 2015-04-27 13:34
> a ha! i missed that ^_^~. You need add dockbar, gadget feature to OS.js

Don't know if it *needs* it, but it might be cool to have:)

**Comment by khoaakt** [comment] 2015-04-27 13:37
don't you see ;), windows have bar(you can pin app to launch it), ubuntu have sidebar,...
And search app feature too~!

**Comment by khoaakt** [comment] 2015-04-27 13:38
Yeah, i tried to rename file but it loading a min and display error.

**Comment by andersevenrud** [comment] 2015-04-27 13:40
@khoaakt I have never used gadgets and fancy bars on my computer. I only have a background image and terminals, hehe. So I am not a big fan. But I will have a look at it :)

> And search app feature too~!

Sure. This could be done, but will have to be placed in the "Touch Menu" (you can change it in Settings)

**Comment by khoaakt** [comment] 2015-04-27 13:43
And in future, OS.js will be like Chrome OS, Firefox OS,.. . This will be compile to a linux kernel and run in mobile, tv, laptop,...

**Comment by andersevenrud** [comment] 2015-04-27 13:45
> And in future, OS.js will be like Chrome OS, Firefox OS,.. . This will be compile to a linux kernel and run in mobile, tv, laptop,...

You can run it like that already, but is not really the goal of OS.js.

https://github.com/andersevenrud/OS.js-v2/blob/master/INSTALL.md#x11

**Comment by khoaakt** [comment] 2015-04-27 13:47
I'm sorry :(, i can't support to programming OS.js because i interested at .NET language but i can tell some way to go for OS.js

**Comment by andersevenrud** [comment] 2015-04-27 13:49
You could always learn a bit of JavaScript and join in on the fun! ;)

Thanks for the suggestions  (i took the freedom to change your post description so it is a bit clearer) :)

**Comment by khoaakt** [comment] 2015-04-27 13:51
*haha*, because i'm Vietnamese then i'm not good at English :)

**Comment by khoaakt** [comment] 2015-04-27 14:15
Hump... something not right :P. OS.js isn't have any terminal :lol

**Comment by andersevenrud** [comment] 2015-04-27 14:25
> Hump... something not right :P. OS.js isn't have any terminal :lol

That's because I don't see the point to be honest. Who wants to use the web browser to type in commands ?! hehe :P 

I have a Terminal client sitting here that I never added to the source-code ready for use though. Maybe I should add it to the "experimental" repository

**Comment by khoaakt** [comment] 2015-04-27 14:47
i have an idea! put terminal in setting, user can turn on/off it :tada:

**Comment by andersevenrud** [comment] 2015-04-27 14:51
@khoaakt No need. You can just build OS.js without the package (or simply disable it in manifest). Making an option in Settings is kinda redundant

**Comment by khoaakt** [comment] 2015-04-27 14:56
If you plan OS.js that run in touch screen, make a visual keyboard :)

**Comment by andersevenrud** [comment] 2015-04-27 15:05
Don't they already have that ? At least my touch devices do :P

**Comment by khoaakt** [comment] 2015-04-27 15:11
A Update? Did OS.js have a update ?(I means OS.js update, it's download update file from server and  pack directly into OS core)

**Comment by andersevenrud** [comment] 2015-04-27 15:12
Sorry, I don't understand what you mean. 

You have to update OS.js manually, either by `git pull` when running from source or unpack a fresh zip from github (overwrite old files).

**Comment by khoaakt** [comment] 2015-04-27 15:13
oh, it just like Windows Update :P

**Comment by andersevenrud** [comment] 2015-04-27 15:17
git and distribution packages are much better in my opinion. I could maybe add update function to the web installer we talked about, but not inside OS.js.

**Comment by khoaakt** [comment] 2015-04-27 15:20
oh ! That is nice idea ;). An update from outside os is more useful. But you need have a admin account to access the admin system control

**Comment by khoaakt** [comment] 2015-04-28 15:43
I'm not interested at code in OS.js :(. Please convert some apps i post to OS.js @andersevenrud 
(Note: this package contains app i posted but i made it. I'm collecting it from internet :P)
Link: http://khoaakt.w.pw/file/App.zip
... And we need a web browser app, i'll post it later :)

**Comment by khoaakt** [comment] 2015-04-30 08:51
Take a look at this:
![image](https://cloud.githubusercontent.com/assets/6000592/7409443/c3ef2510-ef50-11e4-88a5-438bc729343e.png)

**Comment by khoaakt** [comment] 2015-05-01 04:39
hey @andersevenrud, do OS.js have a is-online function? If not, add that to API. That need to dev some app that need internet to run ;)

**Comment by andersevenrud** [comment] 2015-05-01 13:33
@khoaakt Yes it has. You can test it by disabling internet access. A message will be disaplayed warning you

**Comment by khoaakt** [comment] 2015-05-01 16:42
do you think add a web browser is a bad idea? i think it need because os.js will run in a linux-kernel without node

**Comment by andersevenrud** [comment] 2015-05-01 16:45
To create a web-browser application you would have to set up a proxy, or else it will not work because of the Same-Orgin Policy. It does not make much sence to have it in a browser-deployed environment, but it may be useful for running in X11/Standalone. However, this is on the bottom of the priority list.

**Comment by khoaakt** [comment] 2015-05-01 17:12
really? if need, i will create a web browser for os.js. Let me do that :-)

**Comment by MrSchism** [comment] 2015-05-01 17:31
Looks like I should weigh in here (sorry about going dark).

As for a dock, that might be nice, but I'd put that really low on priority.  You can move the current panel to the bottom to replicate the traditional desktop paradigm.

Regarding a slideshow, I'd like to see a front end developed for dzslides (which would probably be easiest to implement in os.js).

**Comment by andersevenrud** [comment] 2015-05-01 18:32
@khoaakt I won't stop you ;)

**Comment by andersevenrud** [comment] 2015-05-01 18:40
@MrSchism I've been away for a while too. Had to take a break. I started having serious *tetris syndrome* symptoms because of too much coding, hehe :p 

Yeah, something like that could be cool. I have not checked into any of these types of apps before, because I've never had any use for them. There's proabably a few to choose from. Know any more worth looking at ?

I'm going to focus getting the last API stuff in place and finish the UI Thingamajigs done.

**Comment by khoaakt** [comment] 2015-05-01 19:36
@andersevenrud Do Application IDE done yet? In this time, IDE is need for develop! Please add that to OS.js as soon as possible ;)

**Comment by khoaakt** [comment] 2015-05-01 19:51
@MrSchism The OS.js dock probably will be in the left/right screen ;)

**Comment by andersevenrud** [comment] 2015-05-01 21:04
@khoaakt No. And to be perfecltly honest, I won't look at it any time soon (Look at the issue tracker... it's full of stuff undone). I suggest you rather start to learn some fundamental JavaScript and CSS. That is all that is required (only the very basics are required). Actually... all you have to know is how to create an object and insert it into the dom and apply styling through CSS.

Here is some info to get you started:
- http://stackoverflow.com/tags/javascript/info
- http://stackoverflow.com/tags/css/info


If you code 18h a day? I am seriously concerned for your health! I hope you take breaks and work out.

**Comment by MrSchism** [comment] 2015-05-01 22:58
When it comes to slide decks, dzslides is probably the easiest to use and implement.  Issue is it would require an editor.  Shouldn't be hard because each slide is a section in a single HTML file.  Should just have to insert tags and render everything inside those tags in the javascript editor.

I know that's how things like the blackboard educational system works:
![screenshot from 2015-05-01 18 55 39](https://cloud.githubusercontent.com/assets/3085862/7438559/0ea8c19a-f034-11e4-9b4a-3829ec280dbe.png)

**Comment by andersevenrud** [comment] 2015-05-01 23:17
@MrSchism Cool. Just googled around, and it seems some of the slide libraries with editors are premium/paid stuff. So it would be cool to have this as a free service. Hosting is no problem.

**Comment by MrSchism** [comment] 2015-05-01 23:33
Prezzi is a paid slide deck; impress.js is a free alternative, but complicated.  DZSlides is free and single file.  The editor above could probably be recreated easily and new slides just have to have a <slide> tag put in.  Might be a minimal side job, but shouldn't be impossible.

**Comment by khoaakt** [comment] 2015-05-02 15:08
@andersevenrud I'm going to learn Javascript ^_^!
P/S: Just kidding, no one can alive when code 18h/day :P

**Comment by andersevenrud** [comment] 2015-05-02 22:13
@khoaakt @MrSchism I'm merging this with #49

**Closed by andersevenrud** 2015-05-02 22:13 UTC
Labels: open for suggestions, request
