### ISSUE TITLE
bugreport: mac os x yosemite

### ISSUE THREAD

**Issue by ManuelArno** [andersevenrud/OS.js-v2#189] opened 2015-12-30 08:31 UTC
This happened after closing the tetris app and starting it again. Also the "press space to start" alert is not vanishing.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot set property 'innerHTML' of null
    at ApplicationTetrisWindow.drawScore (http://osjsv2.0o.no/packages/experiments/Tetris/combined.js:513:29)
    at draw (http://osjsv2.0o.no/packages/experiments/Tetris/combined.js:420:12)
    at frame (http://osjsv2.0o.no/packages/experiments/Tetris/combined.js:429:9)
```

**Comment by andersevenrud** [comment] 2015-12-30 13:45
Duplicate of #190

Thanks for reporting it! I have made a possible fix for this and I will deploy it later today :)

**Closed by andersevenrud** 2015-12-30 13:45 UTC
Labels: duplicate
