### ISSUE TITLE
It doesn't appear to like something with iOS Safari 

### ISSUE THREAD

**Issue by mgmoody42** [andersevenrud/OS.js-v2#217] opened 2015-12-31 17:18 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: 
Line: 0:0
Message: Script error.
```

**Comment by andersevenrud** [comment] 2015-12-31 17:21
Thanks for reporting!

This is a duplicate of #185 and will be looked into ASAP :)

It works after you close the error, right ?

**Closed by andersevenrud** 2015-12-31 17:21 UTC
Labels: duplicate

**Comment by mgmoody42** [comment] 2015-12-31 17:59
I just saw this and revisited the demo. Originally, it would repeat the error, but it closes now.

**Comment by mgmoody42** [comment] 2015-12-31 18:01
As an aside, Tetris in iOS is not very friendly expecting my iPad to have a keyboard. Maybe there is another way to make it work without a keyboard.

**Comment by andersevenrud** [comment] 2015-12-31 18:12
I've had several people test the demo site for me, and so far nobody has been able to replicate it.

I am starting to suspect it might have to do with the Google Analytics that is loaded on the page and it is some kind of connection or network/region issue. I would love to know if this happens if you deploy your own version on the local network and run it on the same device.

I will have to dig further!
