### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by davidthewatson** [andersevenrud/OS.js-v2#186] opened 2015-12-29 23:42 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: 
Line: 0:0
Message: Script error.
```

**Comment by andersevenrud** [comment] 2015-12-29 23:45
Duplicate of #185

I am trying to figure out why some people get this. I suspect a browser plugin. Please look in that issue for more information and debugging

**Closed by andersevenrud** 2015-12-29 23:45 UTC
Labels: duplicate
