### ISSUE TITLE
Crashed while closing the application

### ISSUE THREAD

**Issue by ananthulasrikar** [andersevenrud/OS.js-v2#235] opened 2016-01-03 14:24 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
ApplicationGmailWindow.prototype.updateStatusBar@http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:1681:9
ApplicationGmail.prototype.sync/</<.onMessageQueue@http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:2348:13
_next@http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:889:1
_next/<@http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:909:11
finished@http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:1058:7
GoogleMail.prototype._getMessage/</</<@http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:1080:13
GoogleMailStorage.prototype.addMessage/request.onsuccess@http://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:135:7

```

**Comment by andersevenrud** [comment] 2016-01-03 14:25
Thanks for reporting!

Yeah, the Google Mail app needs some love. I have not looked at it in a while because I have been busy. Now that I have time again I can fix this

This is a duplicate of #216

**Closed by andersevenrud** 2016-01-03 14:25 UTC
Labels: duplicate
