### ISSUE TITLE
issue while re-launching tetris game.

### ISSUE THREAD

**Issue by jafarovr** [andersevenrud/OS.js-v2#196] opened 2015-12-30 16:23 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot set property 'innerHTML' of null
    at ApplicationTetrisWindow.drawScore (http://osjsv2.0o.no/packages/experiments/Tetris/combined.js:513:29)
    at draw (http://osjsv2.0o.no/packages/experiments/Tetris/combined.js:420:12)
    at frame (http://osjsv2.0o.no/packages/experiments/Tetris/combined.js:429:9)
```

**Comment by andersevenrud** [comment] 2015-12-30 16:24
Thanks for reporting in! :)

This is a duplicate of #190

**Closed by andersevenrud** 2015-12-30 16:24 UTC
